export const metadata = { title: 'v0-1773054892083-7jw2u', description: 'Generated by v0' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}